// Code generated by coz. DO NOT EDIT.
/**
 * Drawer for the-components
 * @module the-drawer
 */
'use strict'

import TheDrawer from './TheDrawer'
import TheDrawerStyle from './TheDrawerStyle'

export {
 TheDrawer,
 TheDrawerStyle,
}
